# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d

{'k1': [1,
  2,
  3,
  {'tricky': ['oh', 'man', 'inception', {'target': [1, 2, 3, 'hello']}]}]}

In [6]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
ten = np.zeros(10)
ten

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
five = np.ones(10)*5
five

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [10]:
lst = []
for i in range(20,36):
  if i%2 == 0:
    lst.append(i)
lst
np.array(lst)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [14]:
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])
con = np.concatenate((a1,b1))
con

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [15]:
import pandas as pd

In [17]:
d = {"Name":["a","b","c"], "GENDER":["male","female","male"]}
df = pd.DataFrame(d)
df

Name  GENDER
0    a    male
1    b  female
2    c    male

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [18]:
pd.date_range(start="2023-01-01",end="2023-02-10", freq='B',).tolist()

[Timestamp('2023-01-02 00:00:00', freq='B'),
 Timestamp('2023-01-03 00:00:00', freq='B'),
 Timestamp('2023-01-04 00:00:00', freq='B'),
 Timestamp('2023-01-05 00:00:00', freq='B'),
 Timestamp('2023-01-06 00:00:00', freq='B'),
 Timestamp('2023-01-09 00:00:00', freq='B'),
 Timestamp('2023-01-10 00:00:00', freq='B'),
 Timestamp('2023-01-11 00:00:00', freq='B'),
 Timestamp('2023-01-12 00:00:00', freq='B'),
 Timestamp('2023-01-13 00:00:00', freq='B'),
 Timestamp('2023-01-16 00:00:00', freq='B'),
 Timestamp('2023-01-17 00:00:00', freq='B'),
 Timestamp('2023-01-18 00:00:00', freq='B'),
 Timestamp('2023-01-19 00:00:00', freq='B'),
 Timestamp('2023-01-20 00:00:00', freq='B'),
 Timestamp('2023-01-23 00:00:00', freq='B'),
 Timestamp('2023-01-24 00:00:00', freq='B'),
 Timestamp('2023-01-25 00:00:00', freq='B'),
 Timestamp('2023-01-26 00:00:00', freq='B'),
 Timestamp('2023-01-27 00:00:00', freq='B'),
 Timestamp('2023-01-30 00:00:00', freq='B'),
 Timestamp('2023-01-31 00:00:00', freq='B'),
 Timestamp

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [19]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [20]:
df = pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24